# Generated by Django 5.1.1 on 2024-09-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SQLFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='sql_files/')),
                ('optimized_file', models.FileField(blank=True, null=True, upload_to='optimized_files/')),
                ('compressed_file', models.FileField(blank=True, null=True, upload_to='compressed_files/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
