# Generated by Django 5.1.1 on 2024-09-24 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sqlfile',
            name='compressed_file',
        ),
    ]
