# Generated by Django 5.1.1 on 2024-09-24 17:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0002_remove_sqlfile_compressed_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlfile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
