# Generated by Django 5.1.1 on 2024-09-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0003_sqlfile_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sqlfile',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='sqlfile',
            name='uploaded_file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
